/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nutritionmanagement;

public class App {
    public static void main(String[] args) {
        NutritionAgency nutritionAgency = new NutritionAgency();
        Person p = new Elderly("John", new Active(),nutritionAgency);
        System.out.println(p.description());
        nutritionAgency.setElderlyDietReccomendation("lots of bread");
        nutritionAgency.setElderlyDietReccomendation("broccoli");
        System.out.println(p.description());
    }
}
