/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nutritionmanagement;

public class App {
    public static void main(String[] args) {
        Person p = new Elderly("John", new Active());
        System.out.println(p.description());
    }
}
