/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nutritionmanagement;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class ActivityLevelTests {

    Active act;
    Sedintary sed;
    SlightlyActive sa;


    @BeforeEach
    public void beforeEach() {
    NutritionAgency na = new NutritionAgency();
    act = new Active(na);
    sa = new SlightlyActive(na);
    sed = new Sedintary(na);
    }


    //This test checks to make sure all of the active concrete class constructors work.
    @Test
    void testActiveConstructors() {
        assertNotNull(act, "active constructure returned null");
        assertNotNull(sed, "sedintary constructure returned null");
        assertNotNull(sa, "slightly active constructure returned null");
    }

    //tests the getActivityLevel method for each concrete activity level
    @Test
    void testgetActivityLevelName() {
        assertEquals(act.getActivityLevelName(), "active");
        assertEquals(sed.getActivityLevelName(), "sedintary");
        assertEquals(sa.getActivityLevelName(), "slightly active");

    }

    //tests the getReccomendedCalories method for each concrete activity level    @Test
    @Test
    void testgetReccomendedCalories() {
        assertEquals(act.getReccomendedCalories(), 3200);
        assertEquals(sed.getReccomendedCalories(), 2000);
        assertEquals(sa.getReccomendedCalories(), 2500);
    }

    //tests the setReccomendedCalories method for each concrete activity level    @Test
    @Test
    void testsetReccomendedCalories() {
        act.setReccomendedCalories(0);
        sed.setReccomendedCalories(1);
        sa.setReccomendedCalories(2);
        
        assertEquals(act.getReccomendedCalories(), 0);
        assertEquals(sed.getReccomendedCalories(), 1);
        assertEquals(sa.getReccomendedCalories(), 2);
    }



}
