/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nutritionmanagement;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class PersonTests {

    Elderly e;
    Adult a;
    Teen t;
    Child c;
    NutritionAgency na;
    Active act;
    Sedintary sed;
    SlightlyActive sa;


    @BeforeEach
    public void beforeEach() {
    na = new NutritionAgency();
    act = new Active(na);
    sa = new SlightlyActive(na);
    sed = new Sedintary(na);
	e = new Elderly("John",act,na);
    a = new Adult("Smith",act,na);
    t = new Teen("Tina",sa,na);
    c = new Child("Drake",sed,na);
    }


    //This test checks to make sure all of the people concrete class constructors work.
    @Test
    void testPeopleConstructors() {
        assertNotNull(e, "elderly constructure returned null");
        assertNotNull(a, "adult constructure returned null");
        assertNotNull(t, "teen constructure returned null");
        assertNotNull(c, "child constructure returned null");
    }

    //This test makes sure the observer pattern works and that the observers (concrete people) get updates from the subject (nutrition agency)
    @Test
    void testDietUpdate() {
        na.setElderlyDietReccomendation("elddiet");
        na.setAdultDietReccomendation("alddiet");
        na.setTeenDietReccomendation("teediet");
        na.setChildDietReccomendation("chidiet");
        
        assertEquals(e.getDietReccomendation(), "elddiet");
        assertEquals(a.getDietReccomendation(), "alddiet");
        assertEquals(t.getDietReccomendation(), "teediet");
        assertEquals(c.getDietReccomendation(), "chidiet");
    }

    //This test checks that the bridge pattern works and that the concrete person has a correct activity level
    @Test
    void testActivity() {
        assertEquals(e.getActivityLevel(),act);
        assertEquals(a.getActivityLevel(),act);
        assertEquals(t.getActivityLevel(),sa);
        assertEquals(c.getActivityLevel(),sed);
    }

}
